first_name = input("FIRST NAME: ")
last_name = input("LAST NAME: ")
email = input("Email Address: ")
phone_number = input("Phone Number: ")
job_title = input("Job Title: ")
id_number = input("ID Number: ")
advanced_training = input("Advanced Training Y/N: ")
month_year = input("Start Month and Year: ")
hair_color = input("Hair Color: ")
eye_color = input("Eye Color: ")


print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job_title.capitalize())
print(id_number)
print()
print(email)
print(phone_number)
print(advanced_training)
print(month_year)